image: julia:1.9

before_script:
  - apt-get -qq update; apt-get -y install git python3-dev python3-pip
  - pip3 install css-html-js-minify
    
pages:
  stage: deploy
  script:
    - julia --project=@. -e 'import Pkg; Pkg.instantiate();
      Pkg.add(PackageSpec(name="Franklin", version="0.10.69"));
      using NodeJS; run(`$(npm_cmd()) install highlight.js`);
      using Franklin;
      clear();
      serve(single=true);
      optimize(minify=true, prerender=true)'
    - mv __site public
  artifacts:
    paths:
      - public
  only:
    - main

